### ISSUE TITLE
Add QueueableSource:setVolume()

### ISSUE THREAD

**Issue by pgimeno** [LPGhatguy/love-microphone#11]
LÖVE's `Source` class has a `setVolume` method to set the individual volume of a source. Please add it to `QueueableSource`.

For me it was as simple as:

```diff
diff --git a/love-microphone/QueueableSource.lua b/love-microphone/QueueableSource.lua
index b44ed1c..547e0fa 100644
--- a/love-microphone/QueueableSource.lua
+++ b/love-microphone/QueueableSource.lua
@@ -225,4 +225,8 @@ function QueueableSource:isPaused()
        return (state[0] == al.AL_PAUSED)
 end
 
+function QueueableSource:setVolume(vol)
+       al.alSourcef(self._source, al.AL_GAIN, vol)
+end
+
 return QueueableSource
\ No newline at end of file
```

but I'm not sure if it needs any additional checks.

**Comment by LPGhatguy** [comment]
Beyond checking of the volume argument (which is something I need to do for other parameters too) this shouldn't be that bad to implement.

I'll land this as-is and get on that in another issue, but thank you for the suggestion!

**Comment by LPGhatguy** [comment]
Merged in the latest master!
