### ISSUE TITLE
Changes needed for (my) linux

### ISSUE THREAD

**Issue by miko** [LPGhatguy/love-microphone#5]
Hello,
I tried this on arch linux, and it does not work out of the box. The reason is that this condition from Device:poll() in Device.lua is never met:
```
  if (samplesIn >= self._sampleSize) then
```
somehow the returned number of samples is always lower than sampleSize.
As a workaround, I changed sampleSize to this:
```
  sampleSize = math.floor(frequency * sampleLength * 0.8 )
```
in Device:new(), and it now works for me.

**Comment by LPGhatguy** [comment]
Do you know what backend OpenAL is using when things fail? Was it PulseAudio perchance?

**Comment by miko** [comment]
Yes indeed, it was pulseaudio.

**Comment by LPGhatguy** [comment]
I'm working with KittyCat in the OpenAL IRC on this; it looks like it's most likely an OpenAL or PulseAudio issue. Thanks for the report!

**Comment by LPGhatguy** [comment]
In the latest couple updates (0.4.2 and 0.4.3) I've done everything I can to prevent issues like this from cropping up. I'm closing the issue now, but feel free to reopen it if you test the latest version again and see the same problem.

**Comment by miko** [comment]
Works OK now. Thanks!
