### ISSUE TITLE
Getting SoundData

### ISSUE THREAD

**Issue by rfajfar** [LPGhatguy/love-microphone#8]
Is there a simple way to get **SoundData** after its recorded? I'd like to save it into a table and loop at will.

I'm able to save the current data like `sample_table[key] = source` but because of its **QueueableSource** type it can't loop. I'd like to extract it in the **SoundData** format if possible or something similar.

**Comment by LPGhatguy** [comment]
When you get data from the callback/event, it's in the form of a SoundData. You can manually copy the samples out of it if you want to store it because the object is reused.
